Fix Perl syntax error in Authentication.pm
Fixed syntax error on line 46 where double curly braces {{ }} caused
parsing ambiguity. Changed to use +{ } syntax to explicitly indicate
hash reference constructor.

Error: syntax error near '[]' at Authentication.pm line 46